const Types = {
  SET_WAP_FAVOURITE_GAMES: 'SET_WAP_FAVOURITE_GAMES',
  LOCAL_WAP_FAST_SET_LIMIT_LIST: 'LOCAL_WAP_FAST_SET_LIMIT_LIST',
  LOCAL_WAP_FAST_SET_GAMES_LIMIT_LEVEL: 'LOCAL_WAP_FAST_SET_GAMES_LIMIT_LEVEL'
}

export default Types;
